In [1]:
import tensorflow as tf

node1 = tf.constant(5.0)
node2 = tf.constant(4.0)

c = node1*node2

print(node1, node2)
print(c)

Tensor("Const:0", shape=(), dtype=float32) Tensor("Const_1:0", shape=(), dtype=float32)
Tensor("mul:0", shape=(), dtype=float32)


In [2]:
# Running a computational graph
# Method 1 : Create a TF Session 
sess = tf.Session()
print(sess.run([node1,node2]))
print(sess.run([c]))

[5.0, 4.0]
[20.0]


In [3]:
# Running a computational graph
# Method 2 : Creating TF Session. 
# Session gets automatically closed once computation is done.
with tf.Session() as sess:
    output = sess.run([node1,node2])
    print(output)
    print(sess.run([c]))

[5.0, 4.0]
[20.0]


In [5]:
# Tensorboard
# sess.graph is used for creating graph object
File_Writer = tf.summary.FileWriter('graph',sess.graph)

In [ ]:
# Constants
import tensorflow as tf

node1 = tf.constant(5.0)
node2 = tf.constant(4.0)

c = node1*node2

print(node1, node2)
print(c)


In [7]:
# Placeholders
import tensorflow as tf

node1 = tf.placeholder(tf.float32)
node2 = tf.placeholder(tf.float32)

adder_node = node1 + node2

sess = tf.Session()

print(sess.run(adder_node,{node1:[1,3],node2:[2,4]}))

[3. 7.]


In [26]:
# Variables
# While training variables are used to hold & update weights

import tensorflow as tf

# Model Parameters
W = tf.Variable([.3],tf.float32)
b = tf.Variable([-.3],tf.float32)

# Inputs and Outputs
x = tf.placeholder(tf.float32)

linear_model = W*x + b

y = tf.placeholder(tf.float32)

# Loss
squared_delta = tf.square(linear_model - y)
loss = tf.reduce_sum(squared_delta)


#Initialize all variables
init = tf.global_variables_initializer()

sess = tf.Session()

sess.run(init)


print(sess.run(linear_model,{x:[1,2,3,4],y:[0,-1,-2,-3]}))
print(sess.run(y,{x:[1,2,3,4],y:[0,-1,-2,-3]}))
print(sess.run(linear_model - y,{x:[1,2,3,4],y:[0,-1,-2,-3]}))
print(sess.run(squared_delta,{x:[1,2,3,4],y:[0,-1,-2,-3]}))
print(sess.run(loss,{x:[1,2,3,4],y:[0,-1,-2,-3]}))

# Values
# linear_model = [0., 0.3, 0.6, 0.90000004]
# y = [ 0., -1., -2., -3.]
# linear_model - y = [0., 1.3, 2.6, 3.9]
# squared_delta = [ 0. , 1.6899998 , 6.7599993 , 15.210001 ]


# Note :
# If we take, w = 0.3 & b = -0.3
# w * x + b = 0.3*1 + (-0.3) = 0 
# w * x + b = 0.3*2 + (-0.3) = 0.3
# w * x + b = 0.3*3 + (-0.3) = 0.6
# w * x + b = 0.3*4 + (-0.3) = 0.9
# Loss = 0

# Note :
# If we take, w = -1 & b = 1
# w * x + b = 0, = -1*1 + 1 = 0
# w * x + b = -1  = -1*2 + 1 = -1
# w * x + b = -2
# w * x + b = -3
# Loss = 0


[0.         0.3        0.6        0.90000004]
[ 0. -1. -2. -3.]
[0.  1.3 2.6 3.9]
[ 0.         1.6899998  6.7599993 15.210001 ]
23.66


In [10]:
# Manually updating the weights for 0 l

import tensorflow as tf

# Model Parameters
W = tf.Variable([-1.0],tf.float32)
b = tf.Variable([1.0],tf.float32)

# Inputs and Outputs
x = tf.placeholder(tf.float32)

linear_model = W*x + b

y = tf.placeholder(tf.float32)

# Loss
squared_delta = tf.square(linear_model - y)
loss = tf.reduce_sum(squared_delta)

#Initialize all variables
init = tf.global_variables_initializer()

sess = tf.Session()

sess.run(init)

print(sess.run(loss,{x:[1,2,3,4],y:[0,-1,-2,-3]}))

0.0


In [ ]:
# Over here, we have manually updated the weights but if we want the machine to do it for us.
# We need optimisers.

In [19]:
# Reducing the loss
# Manually updating the weights for 0 loss

import tensorflow as tf

# Model Parameters
W = tf.Variable([-1.0],tf.float32)
b = tf.Variable([1.0],tf.float32)

# Inputs and Outputs
x = tf.placeholder(tf.float32)

linear_model = W*x + b

y = tf.placeholder(tf.float32)

# Loss
squared_delta = tf.square(linear_model - y)
loss = tf.reduce_sum(squared_delta)

# Optimizer
optimizer = tf.train.GradientDescentOptimizer(0.01)
train = optimizer.minimize(loss)

#Initialize all variables
init = tf.global_variables_initializer()

sess = tf.Session()

sess.run(init)

for i in range(1000):
    sess.run(train,{x:[1,2,3,4],y:[0,-1,-2,-3]})
    
print(sess.run([W,b]))    

[array([-1.], dtype=float32), array([1.], dtype=float32)]


In [11]:
# Implement AND Gate using TensorFlow

import tensorflow as tf

T, F =  1., -1.

bias = 1.0

train_in = [
    [T, T, bias],
    [T, F, bias],
    [F, T, bias],
    [F, F, bias]
]

train_out = [
    [T],
    [F],
    [F],
    [F]
]

# Defining a random variable
w = tf.Variable(tf.random_normal([3,1]))

def step(x):
    is_greater = tf.greater(x,0)
    as_float = tf.to_float(is_greater)
    doubled = tf.multiply(as_float,2)
    return tf.subtract(doubled, 1)

output = step(tf.matmul (train_in, w))
error = tf.subtract( train_out, output)
mse = tf.reduce_mean(tf.square(error))

delta = tf.matmul(train_in, error, transpose_a=True)
train = tf.assign(w, tf.add(w, delta))

sess = tf.Session()
sess.run(tf.initialize_all_variables())

err, target = 1, 0
epoch, max_epoch = 0, 10

while err > target and epoch < max_epoch:
    epoch += 1
    err, _ = sess.run([mse, train])
    print('epoch: ', epoch, 'mse: ', err)

Instructions for updating:
Use `tf.global_variables_initializer` instead.
epoch:  1 mse:  1.0
epoch:  2 mse:  2.0
epoch:  3 mse:  0.0
